### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by genjikowa** [halmk/ClipHype#113]
I really don't know how to make your bot work but it looks interesting, i am waiting for you to talk to me, u have discord?

**Comment by halmk** [comment]
@genjikowa thank you for your interest :) I have discord and you can add me on halmk#9213. (but English isn't my first language, please let me know if you don't understand.)
About this app, this app works on following website cliphype.com and you can create a highlights video by sending a create request bottom of the website after login, select a streamer and select clips.

**Comment by genjikowa** [comment]
I have added you on discord, when you can accept me, thanks for the info!
